version: '2'
services:
  db:
    image: postgres
    #container_name: db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      
  redis_db:
    image: 'redis:4.0-alpine'
    container_name: redis_db
    #command: redis-server --requirepass yourpassword
    command: redis-server
    volumes:
      #- 'redis:/data'
      - 'redis:/text-track-service/tmp/redis'

  tts_faktory:
    image: contribsys/faktory:1.5.0
    command: /faktory -b :7419 -w :7420
    ports:
      - "7419:7419"
      - "7420:7420"
    environment:
      FAKTORY_PASSWORD: "${PASSWORD}"
    volumes:
      #- 'faktory:/data'
      - 'faktory:/text-track-service/tmp/faktory'

  website: &web_base
    #container_name: website
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/text-track-service
    ports:
      - "4000:4000"
    depends_on:
      - db
  
  service:
    build: .
    command: "bundle exec ruby ./text-track-service.rb"
    environment:
      #FAKTORY_PASSWORD: "parthik"
      FAKTORY_PROVIDER: FAKTORY_URL
      FAKTORY_URL: tcp://:${PASSWORD}@tts_faktory:7419
    depends_on: 
      - redis_db

  edit_service:
    build: .
    command: "bundle exec ruby ./text-track-edit-service.rb"
    environment:
      #FAKTORY_PASSWORD: "parthik"
      FAKTORY_PROVIDER: FAKTORY_URL
      FAKTORY_URL: tcp://:${PASSWORD}@tts_faktory:7419
    depends_on: 
      - redis_db

  worker:
    build: .
    command: "bundle exec faktory-worker -r ./text-track-worker.rb"
    environment:
      #FAKTORY_PASSWORD: "parthik"
      FAKTORY_PROVIDER: FAKTORY_URL
      FAKTORY_URL: tcp://:${PASSWORD}@tts_faktory:7419
    volumes_from: 
      - website
      
volumes:
  redis:
  faktory:
  #website:
